# Copyright CNOE Contributors (https://cnoe.io)
# SPDX-License-Identifier: Apache-2.0

"""Async HTTPX wrapper around the Webex REST API.

Only the calls the inbound bridge needs:

* ``get_me()`` -- look up the bot's own personId so we can drop
  events generated by the bot itself (loop guard).
* ``get_message(message_id)`` -- fetch the actual message body. Webex
  webhooks deliver only an id; the body must be fetched explicitly.
* ``list_webhooks()`` / ``create_webhook()`` -- ensure exactly one
  ``messages.created`` webhook is registered on the bot's behalf.

Errors propagate as ``httpx.HTTPStatusError`` so callers decide how
to handle failures.
"""

from __future__ import annotations

from typing import Any

import httpx


class WebexClient:
    """Bot-token-authenticated client for the Webex REST API."""

    def __init__(
        self,
        token: str,
        *,
        base_url: str,
        timeout: float = 15.0,
    ) -> None:
        self._client = httpx.AsyncClient(
            base_url=base_url.rstrip("/"),
            headers={"Authorization": f"Bearer {token}"},
            timeout=timeout,
        )

    async def aclose(self) -> None:
        await self._client.aclose()

    # ------------------------------------------------------------------
    # People
    # ------------------------------------------------------------------

    async def get_me(self) -> dict[str, Any]:
        """Return the authenticated bot's own ``person`` record.

        Used by the dispatcher to drop events generated by the bot.
        """
        resp = await self._client.get("/people/me")
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------------
    # Messages
    # ------------------------------------------------------------------

    async def get_message(self, message_id: str) -> dict[str, Any]:
        """Return the full Webex message record for ``message_id``.

        Webex webhook events only include the message id, so the bridge
        fetches the body over an authenticated channel.
        """
        resp = await self._client.get(f"/messages/{message_id}")
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------------
    # Webhook registration
    # ------------------------------------------------------------------

    async def list_webhooks(self) -> list[dict[str, Any]]:
        resp = await self._client.get("/webhooks")
        resp.raise_for_status()
        return resp.json().get("items", []) or []

    async def create_webhook(
        self,
        *,
        name: str,
        target_url: str,
        resource: str = "messages",
        event: str = "created",
        secret: str | None = None,
        filter_expression: str | None = None,
    ) -> dict[str, Any]:
        """Register a Webex webhook for ``resource``/``event`` on ``target_url``.

        ``secret`` enables Webex's HMAC-SHA1 signing of every delivery
        (header ``X-Spark-Signature``). Strongly recommended -- without
        it any client that knows the public URL can forge events.
        """
        body: dict[str, Any] = {
            "name": name,
            "targetUrl": target_url,
            "resource": resource,
            "event": event,
        }
        if secret is not None:
            body["secret"] = secret
        if filter_expression is not None:
            body["filter"] = filter_expression
        resp = await self._client.post("/webhooks", json=body)
        resp.raise_for_status()
        return resp.json()

    async def delete_webhook(self, webhook_id: str) -> None:
        resp = await self._client.delete(f"/webhooks/{webhook_id}")
        resp.raise_for_status()
